### ISSUE TITLE
C++ style "iterators" - is it possible?

### ISSUE THREAD

**Issue by vitalif** [tidwall/btree.c#1]
Hi, can you implement something similar to C++ style iterators?
I was searching for a btree_map library with dynamically sized item support and your library is the only one I've found up until now. :-)
However, iterating via a callback doesn't seem too convenient...

**Comment by tidwall** [comment]
Iterators are currently out of scope.
I may reconsider in the future.

**Comment by tidwall** [comment]
I've reconsidered and added basic loop-based iteration to the recent release.

```c
struct btree_iter *iter = btree_iter_new(btree);
bool ok = btree_iter_seek(iter, key);
while (ok) {
    item = btree_iter_item(iter);
    // ... do something with item ...
    ok = btree_iter_next(iter);
}
btree_iter_free(iter);
```
